
set_property IOSTANDARD LVCMOS33 [get_ports iUART_Clock]
set_property IOSTANDARD LVCMOS33 [get_ports iReset]
set_property IOSTANDARD LVCMOS33 [get_ports iData]
set_property IOSTANDARD LVCMOS33 [get_ports oNew_Data_Valid]
set_property IOSTANDARD LVCMOS33 [get_ports oParity_Error]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oData[0]}]
set_property PACKAGE_PIN H16 [get_ports iUART_Clock]
create_clock -name iUART_Clock -period 104166.6 [get_ports iUART_Clock]

#set_property -dict {PACKAGE_PIN H16 [get_ports iUART_Clock]} [get_ports iUART_Clock]
#create_clock -add -name sys_clk_p -period 10 -waveform {0 5} [get_ports iUART_Clock]
